apiVersion: v1
kind: Service
metadata:
  name: snapshot-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: snapshot-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 10450
    protocol: TCP
  selector:
    app: snapshot-frontend

